### ISSUE TITLE
Docdiff: investigate why it breaks other integrations

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#11]
Docdiff works correctly currently. However, I had to disable it for now because it interferes with other integrations like EthicalAds and Search As You Type.

I assume that it breaks because it changes the DOM and it may be removing some things required for the other integrations? 🤷🏼

**Comment by agjohnson** [comment]
This is probably because doc-diff replaces the DOM at `config.root_selector`:

https://github.com/readthedocs/doc-diff/blob/main/src/extension.js#L166

It should probably be loaded last, after all other DOM manipulations are finalized.

**Comment by humitos** [comment]
Hrm... I just realized that all those `promises` are working in a sync way because I'm calling them directly. I have to create a `new Promise()` if I want them to be async.

**Comment by agjohnson** [comment]
Well, you have three layers of promises so far: the outside promise signalling loading state, the promises for each tool, and the return from `Promise.all(...)` (this is also a promise [^1]). You'd want to chain on to the return value from `Promise.all(...)`, where you do have `config` scoped. So, something like:

```js
return Promise.all(
  promises
).then(() => {
  return docDiff.initialize(config);
});
```

**Comment by agjohnson** [comment]
>  I have to create a new Promise() if I want them to be async.

I didn't look closely, but this is generally the issue that makes async code hard. Everything needs to be async to take advantage of async operations. For the purposes of this first iteration, it will be easier to avoid promises/async execution.

**Comment by humitos** [comment]
I updated the code to make it a little cleaner and show what I'm trying to do and how I'm chaining the `Promise`s. It still doesn't work, because for some reason is not calling `initializeDocDiff` now, but 🤷🏼 

https://github.com/humitos/readthedocs-client/blob/a78b2fd74b5b783cb6b5c326a70f0fe438f8169d/src/index.js#L73-L77

**Comment by agjohnson** [comment]
It looks like you're not resolving the promises here: https://github.com/readthedocs/readthedocs-client/blob/main/src/index.js#L67-L69

This would leave the Promise waiting for resolve/reject, and your `then(...)` will never be reached. You will need to call that `resolve` callback function to tell the Promise to resolve. Something like:

```js
for (let fn of integrations) {
  promises.push(
    new Promise((resolve) => {
      resolve(fn(config));
    })
  );
}
```

`Promise` also gets a reject argument on the promise callback. This can be used to trigger error handling farther up on the Promise chain:

```js
return new Promise((resolve, reject) => {
   ...
   reject(new Error("Oops!"));
});
```

Promises tend to have a steep learning curve. Native async code is a bit easier to understand in comparison, as there are lots of ways to shoot your foot with promises.
