### ISSUE TITLE
Flyout: scroll the menu when there is too many versions

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#121]
![Peek 2023-09-11 15-33](https://github.com/readthedocs/addons/assets/244656/ae53fb79-ab66-4763-b029-57e59add5ab6)

Related: https://github.com/readthedocs/readthedocs.org/pull/7375

**Comment by zanderle** [comment]
Do we also want to make the header of the flyout sticky, so that it is always shown, even when we scroll down?

**Comment by humitos** [comment]
> Do we also want to make the header of the flyout sticky, so that it is always shown, even when we scroll down?

Yes. That would be great 👍🏼

**Comment by zanderle** [comment]
> > Do we also want to make the header of the flyout sticky, so that it is always shown, even when we scroll down?
> 
> Yes. That would be great 👍🏼

Oops, that PR didn't include this yet. Do you want me to reopen this or create a separate issue?

**Comment by humitos** [comment]
@zanderle a separate issue is fine.
