### ISSUE TITLE
Pattern to handle exceptions

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#122]
Anthony made some suggestions about handling exceptions with `try`/`catch` in

* https://github.com/readthedocs/addons/pull/118#discussion_r1321828523
* https://github.com/readthedocs/addons/pull/118#discussion_r1321859324
* https://github.com/readthedocs/addons/pull/119#discussion_r1321875255

I'd like to find a standard pattern to follow on all the addons that complies with the following ideas, if possible:

* does not involve adding a try/catch each time we want to access a field
* validate the `config.addons.<name>` only once at initialization time and not enable it if it's not valid
* does not break other addons if it fails (e.g. invalid data on `hotkeys` addon doesn't break `search`)
* it's simple to understand and communicate to other team members 😉 

What is a good way to implement this idea? Is this idea good? Are there already standard patterns that I'm not aware of?

**Comment by agjohnson** [comment]
So, I see a few options:

- We maintain a default data structure and deep merge that with the user provided configuration. We still need to be defensive around code that assumes data structure properties though.
- Try/catch each time we touch the config object. This is a lot of redundant code.
- Wrapper the configuration in another layer and avoid exceptions trying to read deeply nested properties. This might be my preference, as it avoid exceptions and doesn't require maintaining a configuration schema.

The wrapper layer could be something along the lines of [object path](https://www.npmjs.com/package/object-path), which gets us a `.get()` that works on deeply nested structures. This won't change our code much, and supports default values so we can avoid exceptions from missing data.

**Comment by humitos** [comment]
He, I just found this exception in commercial: https://docs.ops.verbthenouns.com/projects/test-builds/en/manual-integrations/

![Screenshot_2023-09-12_19-17-57](https://github.com/readthedocs/addons/assets/244656/cb30ebbe-dba3-4552-9397-968f25645270)

**Comment by humitos** [comment]
We talked a little about this while working on #73

**Comment by humitos** [comment]
We are now using a JSON schema validation to validate the `config` part the addon is interested about. If there are missing keywords or invalid value types, the addon won't be enabled. I'm closing this issue since we are happy with the current pattern and we are working on expanding it more as we continue moving forward.
