### ISSUE TITLE
Flyout: keep version on lang switch

### ISSUE THREAD

**Issue by trasher** [readthedocs/addons#130]
## Details

* Read the Docs project URL: https://glpi-install.readthedocs.io/en/develop/install/advanced-configuration.html

Currently, the above page exists only in the develop version of the documentation. 
When switching to another language; current version should be kept but is not (just try to switch to another language).

## Expected Result

User is redirected to the current page on **current** version with selected lang.

## Actual Result

User is redirected to the current page on **latest** version with selected lang (page that does not exists).

**Comment by humitos** [comment]
This change is deployed. Now, switching between versions/languages from the flyout addons will keep the page the user is looking at on the version/language destination.

**Comment by trasher** [comment]
Thank you very much! :)
