### ISSUE TITLE
latest page displays warning

### ISSUE THREAD

**Issue by miketheman** [readthedocs/addons#139]
Hi there! We use ReadTheDocs for a couple of sites, and noticed that our stable pages appear to ahve a notice on them making it seem they are not the latest.

<img width="1074" alt="Screenshot 2023-09-19 at 14 11 42" src="https://github.com/readthedocs/addons/assets/529516/02ea57de-4163-46ea-b50e-cebf0a304bc6">

https://warehouse.pypa.io/
https://blog.pypi.org/

These sites have this checkbox selected, if that changes how things are evaluated:

![hmmmm](https://github.com/readthedocs/addons/assets/529516/56e54bf3-4717-4abd-ad1e-bbe0b4538be2)

I don't know exactly where the bug lies, but it seems likely to be related to https://github.com/readthedocs/addons/issues/71

cc @ewdurbin @di

**Comment by stsewd** [comment]
Hi, looks like a bug, we aren't taking into consideration the case of single version projects. I'm looking into a way to disable this feature for your projects in the meantime.

**Comment by stsewd** [comment]
This feature should be disabled for those two projects now.

**Comment by miketheman** [comment]
Thanks for the speedy handling @stsewd ! I can confirm things looks clear now. Do we need to have anything else done after the bug has been fixed?

**Comment by stsewd** [comment]
> Do we need to have anything else done after the bug has been fixed?

Nope, going to track this at https://github.com/readthedocs/addons/issues/140.
