### ISSUE TITLE
Forwards compatibility (error handling)

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/addons#17]
The overall question is how do static websites work in 5-10 years and how many legacy APIs do we expect to be around by then.

The solutions are perhaps found in some sense of user-oriented error handling.

* Does the API respond? What if it doesn't?
* _When_ were the docs generated (at what date)? Do we have a customized message in case docs are _really old_ and the API isn't around?
* Can the version warning banner help?
* Are reasonable fallbacks possible? What reliable resources can help when others are failing? For instance, a link to the "latest version" or the project's page on Read the Docs?

https://github.com/readthedocs/readthedocs.org/issues/8323 is an example of assumptions that may have broken after 5-10 years.

**_This is possibly pretty low priority, just wanted to post these thoughts somewhere :)_**

**Comment by humitos** [comment]
It seems we had an on-going conversation about versioning the flyout at https://github.com/readthedocs/meta/issues/96 as well. So, I'm linking it from here so we can find it again when we continue talking about these topics.

**Comment by humitos** [comment]
We are moving forward with this in some way. We added a HTTP header with the version of the client itself that all the js `fetch` functions send to the API server. The server will have all the scheme responses versioned and will decide, based on that HTTP header, what's the JSON structure that is compatible with the client making the request. This work is happening in https://github.com/readthedocs/readthedocs.org/pull/10216
