### ISSUE TITLE
Search: prevent triggering other integrations with `/`

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#25]
It seems that `/`, `?`, `Ctrl + f` and `Ctrl + k` are pretty common hotkeys to trigger modals (eg. search, help, etc). We are currently mapping our search modal to `/`.

MkDocs, for example, uses `/` to show a modal with some help about the hotkeys. This conflicts with our own modal:

![Peek 2023-03-29 23-32](https://user-images.githubusercontent.com/244656/228673488-b5dfcbe5-67fe-41c7-990a-c9a804cc953c.gif)

I tried to find how to call `document.removeEventListener("keydown");` but it seems it requires passing the function handler as second attribute. What would be a possible solution for these cases?

**Comment by humitos** [comment]
Interesting. Material for MkDocs also uses `/` to jump into the focus of the search input. However, it does not collide with ours for some reason 🤷🏼 . I'm testing this locally at http://test-builds.devthedocs.org/en/mkdocs-material/

**Comment by humitos** [comment]
Currently, we are injecting our script at the end of `<head>`. Would be possible to solve this issue by injecting our script at the beginning of it, _making it loading in a sync way_ and using `event.preventDefault()`?

**Comment by agjohnson** [comment]
Just wanted to note that `C-f` is a browser shortcut (find in Firefox and others) that we shouldn't override.

> Would be possible to solve this issue by injecting our script at the beginning of it, making it loading in a sync way

We still want to load async or we'll block the page load, so async might still load *after* other async scripts still.

Noted on #115, but I'd probably say we shouldn't do anything unexpected here and let the project maintainer decide this instead. They can control their own project's behavior on keyboard shortcuts.

Long term, we need UI that will trigger these elements, keyboard shortcuts are more of a temporary solution because we don't have this UI.

**Comment by humitos** [comment]
In https://github.com/readthedocs/addons/pull/115#issuecomment-1710908540 we talked about documenting how to disable conflicting hotkeys from other doctools and point users to this documentation: https://github.com/readthedocs/addons/pull/115#issuecomment-1710908540

**Comment by FeeeeK** [comment]
Apparently this does conflict with mkdocs, you can clearly see it [here](https://vkbottle.readthedocs.io/ru/dev/), this documentation uses a custom build process, maybe this is the reason.
Also, clicking on the search string from mkdocs-material opens the readthedocs search and this is very annoying.

https://github.com/readthedocs/addons/assets/26704473/946bd7b0-2fd8-43d7-9c8d-b804a58023dc

**Comment by humitos** [comment]
@FeeeeK thanks for reporting this 👍🏼 . We are working on improving this integration and hopefully we will fix it soon.

> Is there any way to disable this but leave the site indexed?

I disabled the hotkeys addon on that project for now. In the near future, maintainers will be able to enabled/disable these addons by themselves.

**Comment by humitos** [comment]
I didn't find a way to disable the keyboard shortcuts on Material for MkDocs: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#keyboard-shortcuts

**Comment by ericholscher** [comment]
Next steps: document that each tool needs a way to disable hot keys.

**Comment by humitos** [comment]
I wrote some thoughts about this at:

* https://github.com/readthedocs/addons/issues/165#issuecomment-1781287582
* https://github.com/readthedocs/addons/pull/168#issuecomment-1778842061

Summarizing,

* Hotkeys addon should be disabled by default
* Each hotkeys from the addon should be configurable as enabled/disabled (e.g. enable "show search modal" with `/` but disable "docdiff" with `d`)
* We need to document how to disable keyboard shortcuts from known incompatibilities with doctools/plugins/etc and explain how to integrate in a nicer way our owns

With that said, I'm closing this issue and opening a new one about writing the documentation required for this plan.

**Comment by humitos** [comment]
@FeeeeK Hi 👋🏼 . Material for MkDocs released `v9.5.5` that includes a fix for this. Can you upgrade to the latest version of it if haven't already and re-enable the hotkeys addons by going to the new dashboard at https://beta.readthedocs.org/ and then to your project's settings? I'd appreciate that 🙏🏼
