### ISSUE TITLE
Docdiff validation error

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/addons#252]
Screenshot:

![Screenshot from 2024-02-13 10-52-12](https://github.com/readthedocs/addons/assets/25510/43208e0c-8ae1-4d3a-9b1a-e4bd8ee5d9c4)

Viewable here: https://www.ethicalads.io/

**Comment by humitos** [comment]
This was fixed in https://github.com/readthedocs/addons/pull/274. I'm not sure why it wasn't closed automatically.

**Comment by ericholscher** [comment]
Yep, confirmed it's working :+1:
