### ISSUE TITLE
Docdiff: should also respect the `<main>` HTML tag

### ISSUE THREAD

**Issue by mowies** [readthedocs/addons#263]
Right now, from checking the source code, the DocDiff addon just checks for the `role=main` query selector, but it would be cool to also check for a `<main>` HTML tag alternatively, or to be able to configure the main container query selector for the addon.

**Comment by humitos** [comment]
Hi @mowies! Thanks for reporting this issue. Can you please provide a URL for a documentation project where you are experience this issue?

> or to be able to configure the main container query selector for the addon.

We are working on this. The idea is to expose some configurations of the addons via a WebUI in the project's settings. The minimal implementation of enabled/disabled for each addon is available in the new dashboard by going to your project's admin page at https://beta.readthedocs.org/

**Comment by mowies** [comment]
I'm testing out the addon with the preview builds for [this PR](https://github.com/keptn/lifecycle-toolkit/pull/3175).

> We are working on this. The idea is to expose some configurations of the addons via a WebUI in the project's settings. The minimal implementation of enabled/disabled for each addon is available in the new dashboard by going to your project's admin page at [beta.readthedocs.org](https://beta.readthedocs.org/)

cool! that makes a lot of sense, it would be great to be able to define that in code as well though. so probably in the `readthedocs.yml` file?

**Comment by mowies** [comment]
the corresponding preview page for the PR mentioned above is: https://keptn--3175.org.readthedocs.build/3175/docs/guides/auto-app-discovery/

**Comment by humitos** [comment]
> it would be great to be able to define that in code as well though. so probably in the `readthedocs.yml` file?

I don't think this will happen anytime soon, since the configuration file is per-version and these addons settings are per-project. If you are interested, you can read more about this problem with per-project configuration on the config file at https://github.com/readthedocs/readthedocs.org/issues/9188

**Comment by humitos** [comment]
The front end part is done here. However, there is a change in the backend at https://github.com/readthedocs/readthedocs.org/pull/11181 that will allow users to specify a custom selector by using the WebUI. I plan to deploy all these changes on next Tuesdays.

I will write down another comment here after the deploy so you can test by yourself the new feature and let us know if it works as expected.

**Comment by humitos** [comment]
We just deployed this feature. @mowies you should be able to go to the new beta dashboard at https://beta.readthedocs.org/ and go to the settings of your project to define a custom `root selector` there. Please, let me know if it works as you expected 🙏🏼 

![Screenshot_2024-03-12_16-26-21](https://github.com/readthedocs/addons/assets/244656/142cabcb-5664-4a2e-b2db-944d26923062)

**Comment by mowies** [comment]
I tried it out in [this PR](https://github.com/keptn/lifecycle-toolkit/pull/3253) but it has an error during the comparison. Although, I can confirm that the CSS selector works now 👍🏼 

The diff comparison is failing in [this line](https://github.com/readthedocs/addons/blob/main/src/docdiff.js#L136) with the error from the screenshot:
![Screenshot 2024-03-13 at 08 23 17](https://github.com/readthedocs/addons/assets/6901203/ade9d718-33dd-4a30-9579-b06e31a9b848)

**Comment by humitos** [comment]
> The diff comparison is failing in [this line](https://github.com/readthedocs/addons/blob/main/src/docdiff.js?rgh-link-date=2024-03-13T07%3A23%3A41Z#L136) with the error from the screenshot:

Hrm, I think this is an issue about how we import the `visualDomDiff` library. I thought I solved this issue in the past, but the PR was never merged https://github.com/readthedocs/addons/pull/234

I will try to take another look at it and see if I can fix it. I would appreciate any help/suggestion you may have in case you know Javascript 😄

**Comment by humitos** [comment]
@mowies I deployed a fix for the `visualDomDiff` import issue. I checked again on your PR at https://keptn--3175.org.readthedocs.build/3175/docs/guides/auto-app-discovery/ but it seems _the whole page_ is marked as a completely diff. Have you change the theme or re-structuring the underlying HTML or similar?

![Peek 2024-03-13 13-02](https://github.com/readthedocs/addons/assets/244656/265da85d-1bb2-48be-ab12-ce55353b4666)

**Comment by mowies** [comment]
seems like more changed there yeah..
although in my latest test PR it works: https://keptn--3253.org.readthedocs.build/3253/docs/core-concepts/

**Comment by humitos** [comment]
Awesome! That's great! I'm leaving the example here just for reference:

![Peek 2024-03-13 13-09](https://github.com/readthedocs/addons/assets/244656/91e903eb-00d5-4303-ab07-5714a680f8fc)

**Comment by humitos** [comment]
@mowies BTW, thanks for your support on figuring this out! 🙏🏼

**Comment by mowies** [comment]
No worries :)
Thanks for this quick fixes!
