### ISSUE TITLE
Docs: update release steps

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#275]
We have our release process explained at

https://readthedocs-client.readthedocs.io/en/latest/releasing.html

However, with the introduction of `wrangler` in the community/corporate repositories via `common/` submodule, we now require also:

1. update `NGINX_ADDONS_GITHUB_TAG`: https://github.com/readthedocs/common/blob/main/dockerfiles/docker-compose.yml#L29
2. update `common/` submodule on community and commercial as well

To solve 2) in a more generic way, it would be good if we can make `common/` submodule to _always_ point to the latest commit in `main` branch. cc @stsewd do you know if this is possible?

**Comment by stsewd** [comment]
> it would be good if we can make common/ submodule to always point to the latest commit in main branch. cc @stsewd do you know if this is possible?

I don't think so.
