### ISSUE TITLE
Search: default "Include subproject" in the search

### ISSUE THREAD

**Issue by noklam** [readthedocs/addons#289]
Follow up: #209 

<img width="1426" alt="image" src="https://github.com/readthedocs/addons/assets/18221871/3e4048f0-dbbe-498f-93ba-450a6e371a9f">
Mind that funny checkbox is probably our fault with the CSS. Is there a way to check this box by default? Most user wouldn't pay attention to it and we would like to have it checked by default.

cc @astrojuanlu

**Comment by humitos** [comment]
Thanks for opening this issue.

We have plans to expose a way to configure those filters and whether they are enabled/disabled by default.

**Comment by humitos** [comment]
Closing in favor of #22. I'm going to cover this case there, as well.
