### ISSUE TITLE
Search: "Recent searches" does not consider different versions

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#296]
It seems the "Recent searches" shows all the searches performed in the domain. However, in the same domain there could be different versions and even different projects when using subprojects.

We should save the `project.slug` and `version.slug` in the recent searches data to know if they match when restoring them from the cache.

How to reproduce:

1. go to https://test-builds.readthedocs.io/en/latest/
2. search for "configuration"
3. click on the result
4. go to a different version using the flyout
5. click on the search input from the flyout

At this point, you will see the "Recent search" you perform in a different version. If you click there, you will go to the other version.

**Comment by zanderle** [comment]
Yeah, I did not consider this at all. On it.

**Comment by ericholscher** [comment]
I also find the styling of recent searches a bit confusing. I feel like maybe we lost the spinner as well when the search is currently ongoing, so when I do a new search, it's hard to understand that the search is happening and the recent search results aren't the current results. We should likely give them a slight background color or some other UX:
 
![Screenshot 2024-07-03 at 9 20 36 AM](https://github.com/readthedocs/addons/assets/25510/b9ac4111-2c12-4076-b01b-f84091745c28)

**Comment by zanderle** [comment]
> I also find the styling of recent searches a bit confusing. I feel like maybe we lost the spinner as well when the search is currently ongoing, so when I do a new search, it's hard to understand that the search is happening and the recent search results aren't the current results. We should likely give them a slight background color or some other UX:

Hmm, the spinner is indeed not spinning, and I'm not exactly sure why. I just spent 15min on it, and couldn't find anything obvious. Regarding your other comment, should we just hide the recent searches, when the current search starts happening?

**Comment by ericholscher** [comment]
> Regarding your other comment, should we just hide the recent searches, when the current search starts happening?

That seems like a nice simple solution :+1:

**Comment by zanderle** [comment]
@ericholscher I implemented this in https://github.com/readthedocs/addons/pull/353 . I think it works fine, but it's a bit weird when changing the search query - the results are removed when we change the query, and I'm not sure if recent searches should remain hidden in this case or not. Any preferences?

**Comment by ericholscher** [comment]
Not really sure, tbh. Not sure there's a "correct" way, so whatever we do for now is fine, and see if we get any feedback on it.
