### ISSUE TITLE
Allow disable of calculateStableLatestVersionWarning

### ISSUE THREAD

**Issue by itdependsnetworks** [readthedocs/addons#298]
In #281 and specifically within https://github.com/readthedocs/addons/pull/281/files#diff-f9dfa59482e5f89390bb577fa20517bfa243bc3efcd7cdd61f11c9a312c8d851R113-R146 there was a change to the behavior of the popup that shows a message on which version of docs you are looking at. 

Is it possible to disable this message as a configuration option? The comment states "but users with different needs should be able to implement their own custom logic.", but it is not clear to me if that is possible.

**Comment by humitos** [comment]
Hi. Can you expand on what's the problem with the notification? Under what scenarios it's shown and it shouldn't?

**Comment by itdependsnetworks** [comment]
If you are using read the docs a lot and constantly having this pop-up show up. If it was a saved preference that I did once per browser and repo with a stored cookie, I could understand, but every time is really a lot. 

Within my company, I have heard of no less than 4 other people come to the same conclusion.

**Comment by cmsirbu** [comment]
I'll add to this request to make the banner configurable, for a few reasons:

1. It doesn't work well with mkdocs-material, overlapping the nav bar.
2. Once dismissed, it's not sticky (it comes back on every page load), making it incredibly annoying to use. Every single time I want to navigate somewhere, I have to first dismiss the popup.
3. It doesn't respect the browser's dark mode setting, overlaying a light box on a dark theme (see below).
4. For some of our docs sites, `latest` is the default version we want to show users and configured as such in the RTD project. We do not want a banner showing up there all the time confusing things. I think this could be a check that's done server-side per-project.

![image](https://github.com/readthedocs/addons/assets/9288571/b54f0e10-9a55-414f-8972-520b835f0ae6)

**Comment by humitos** [comment]
Hi. I'm from the phone 📱.

1. In #46 we are tracking the improvement for permanently dismissing the notification

2. Regarding configuration/disable of the addon, you can do this from the new dashboard at https://beta.readthedocs.org going to your project settings and then "Addons (Beta)"

Let me know if that helps.

**Comment by cmsirbu** [comment]
> Hi. I'm from the phone 📱.
> 
> 1. In [Notification: use a cookie to keep it closed for the session #46](https://github.com/readthedocs/addons/issues/46) we are tracking the improvement for permanently dismissing the notification
> 2. Regarding configuration/disable of the addon, you can do this from the new dashboard at https://beta.readthedocs.org going to your project settings and then "Addons (Beta)"
> 
> Let me know if that helps.

It helped, thanks a lot @humitos! Was able to disable the banner and loving the fact that it applies instantly :)

Will keep an eye out for updates, especially if you guys address its usability issues I pointed out above - then we can maybe enable it again (since the idea behind it is actually useful).

**Comment by humitos** [comment]
> It helped, thanks a lot @humitos! Was able to disable the banner and loving the fact that it applies instantly :)

💯 

> It doesn't work well with mkdocs-material, overlapping the nav bar.
> It doesn't respect the browser's dark mode setting, overlaying a light box on a dark theme (see below).

The notification is documentation tool agnostic, so I don't think we will change it's style to match Material for MkDocs specifically. However, it can be customized via CSS (we are working on a more generalized pattern for this in #197

**Comment by cmsirbu** [comment]
> > It helped, thanks a lot @humitos! Was able to disable the banner and loving the fact that it applies instantly :)
> 
> 💯
> 
> > It doesn't work well with mkdocs-material, overlapping the nav bar.
> > It doesn't respect the browser's dark mode setting, overlaying a light box on a dark theme (see below).
> 
> The notification is documentation tool agnostic, so I don't think we will change it's style to match Material for MkDocs specifically. However, it can be customized via CSS (we are working on a more generalized pattern for this in #197

Being tool/theme agnostic makes sense, but that indeed means giving the possibility to customize it (location/sizing/stickiness etc.). And it'll help adoption if it at least works well with the most popular themes used out there :)

WRT light/dark mode, that should also be an independent thing that I'd expect your banner to detect from the OS preference exposed by the browser and automatically flip from light to dark.

**Comment by humitos** [comment]
@cmsirbu cool! I've opened an issue at https://github.com/readthedocs/addons/issues/301 to talk about the dark/light mode. I will close this issue for now since the original request was solved. Let's continue talking about this in the new one.
