### ISSUE TITLE
Flyout: add a link to flyout/addons documentation

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#304]
In #302 we removed the Privacy Policy link from the footer, but we didn't have a better one to put there. This issue is to discuss/find a better link to put there. I think it could be one that goes to the Read the Docs Addons documentation page where the addons are explained/documented.

Related:
* https://github.com/readthedocs/readthedocs.org/issues/11187

**Comment by agjohnson** [comment]
Needs documentation first, we'll be blocked on this for now.
