### ISSUE TITLE
Search: initial help when the search modal is opened

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#33]
This may not be _required_ and we could use different approaches here. However, I just thought it could bring a kind of "welcoming message" to have some small help in the initial dialogue of the search modal:

![Screenshot_2023-04-04_00-04-22](https://user-images.githubusercontent.com/244656/229637662-3ee25f3f-05eb-489d-a0e1-bd8a27b8f7a1.png)

"Starting typing to find out results. You can use the following syntax patterns"

I'm thinking we can expose something similar to what we are showing when there are no results at all: https://github.com/readthedocs/readthedocs-client/issues/19#issuecomment-1490175025

Algolia shows "No recent searches" there when there is nothing to show or, the recent searches themselves if there some.

![Screenshot_2023-04-04_00-07-03](https://user-images.githubusercontent.com/244656/229637994-d9b6959e-0ecf-43d6-bbcf-a2efc24f133e.png)

**Comment by humitos** [comment]
GitHub uses `?` to show tips and hints, which could be a good idea:

![Screenshot_2023-07-19_15-28-00](https://github.com/readthedocs/addons/assets/244656/dd6dc8b6-e47a-4697-ae74-94479a64b2e0)

after pressing this key:


![Screenshot_2023-07-19_15-28-10](https://github.com/readthedocs/addons/assets/244656/7541c4e8-de02-4aad-ba0b-c3c458900ed0)

**Comment by humitos** [comment]
> Recent searches sounds like a good idea, but it will involve some extra work - I'm not sure if that's the direction we want or not?

Yeah, this could be a future feature if we find it useful.

**Comment by zanderle** [comment]
@humitos I'm revisiting this, and after looking into it more closely, I don't agree with my initial assessment anymore 😄 

I think recent searches make more sense, given that we're already showing the "tips" when there are no search results. And those tips are about as much additional context as we can provide (unlike the Github example, which offers a few more options).
I also thought of an easier implementation of the recent searches, so I think I'll prepare an example of that and we can see how we like it.

**Comment by humitos** [comment]
@zanderle great! Let me know if you have any questions or different ideas you want to discuss. I'm happy to see a proposal as well and give you feedback 👍
