### ISSUE TITLE
Flyout: display language when collapsed

### ISSUE THREAD

**Issue by nijel** [readthedocs/addons#359]
## What's the problem this feature will solve?

When users browse the documentation, they are unaware that it is available in other languages.

## Describe the solution you'd like

Make the language selection visible in the flyout before expanding (for projects that have multiple languages) similarly like the currently selected version is visible.

## Alternative solutions

The language selection is there, but people won't notice it unless they are aware of the option.

## Additional context

Can be seen at https://docs.weblate.org/en/latest/.

**Comment by humitos** [comment]
I opened https://github.com/readthedocs/addons/pull/360 as an example. I'd appreciate your feedback there.
