### ISSUE TITLE
Integrate with error pages

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/addons#371]
The documentation error pages used to direct users to search in our dashboard with an input. I noted here that we should probably rework the search feature to instead use the in-doc search instead:

- https://github.com/readthedocs/readthedocs.org/issues/11486

One other point to integrating with the error pages is that Addons are active on error pages currently -- flyout, version warnings, etc. These feel a little out of place on error pages, and might be conflicting warnings to readers.

**Comment by agjohnson** [comment]
We should disable the flyout and notifications on error pages probably, otherwise they both show by default:

![image](https://github.com/user-attachments/assets/9521ded3-c884-4a4e-85f6-551ee18a35d8)

We want analytics addon to always run though, and might use search in these UIs eventually. So we shouldn't disable all addons on error pages.

**Comment by humitos** [comment]
> I noted here that we should probably rework the search feature to instead use the in-doc search instead:

👍🏼 

> We should disable the flyout and notifications on error pages probably, otherwise they both show by default
> We want analytics addon to always run though, and might use search in these UIs eventually. So we shouldn't disable all addons on error pages.


URL where you can notice this behavior: https://dev.readthedocs.io/en/latest/notfound.html

I've tried this some time ago and I found that's not possible to know what's the status code for the original documentation URL from JavaScript. I will add the status code using CF Worker and reading it from JavaScript following the pattern we are using to read other similar data we don't have access from JavaScript.

**Comment by humitos** [comment]
I opened these PRs to solve this issue:
* https://github.com/readthedocs/addons/issues/371
* https://github.com/readthedocs/common/pull/222
