### ISSUE TITLE
Retain page when switching version through warning banner

### ISSUE THREAD

**Issue by michellewang** [readthedocs/addons#387]
Hello, 

I noticed that when I click the version switching link on the warning banner (for both dev and old versions), it brings me back to the home page. This is different from the flyout menu, where switching versions retains the page the user is currently viewing. Would it be possible to implement this behaviour in the warning banner too?

Related issues:
- https://github.com/readthedocs/addons/issues/211
- https://github.com/readthedocs/addons/issues/223

**Comment by humitos** [comment]
Do you have an example where the unexpected behavior is happening and how it should behave? Thanks
