### ISSUE TITLE
Flyout: communicate there is features in the expanded version

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#393]
> Also, it's worth noting here that we also dropped the dropdown caret on the right side of the menu. Without this, there isn't a visual cue that the flyout menu expands.

_(from https://github.com/readthedocs/addons/pull/360#issuecomment-2350049920)_

Example of what we had in the old flyout

![Screenshot_2024-10-03_12-18-38](https://github.com/user-attachments/assets/8f313b4b-9200-4286-aa74-60482dd9ba58)

**Comment by ericholscher** [comment]
Seems this is a dupe of https://github.com/readthedocs/addons/issues/364
