### ISSUE TITLE
Search: default Sphinx's search doesn't work when I search Chinese or Janpanese

### ISSUE THREAD

**Issue by lucays** [readthedocs/addons#397]
After addons is enabled, default Sphinx's search doesn't work when I search Chinese:
https://ocg-rule.readthedocs.io/zh-cn/latest/search.html?q=%22%E6%8A%80%E8%83%BD%E6%8A%BD%E5%8F%96%22

or Japanese: https://ocg-rule.readthedocs.io/zh-cn/latest/search.html?q=%22%E3%82%AF%E3%82%A4%E3%83%83%E3%82%AF%E3%82%A8%E3%83%95%E3%82%A7%E3%82%AF%E3%83%88%22

but works normally when I search English:
https://ocg-rule.readthedocs.io/zh-cn/latest/search.html?q=%22quick%22

I can confirm default Sphinx's search can search Chinese or Japanese normally before.

And, addon search api can search Chinese or Japanese:
https://ocg-rule.readthedocs.io/_/api/v3/search/?q=project%3Aocg-rule%2Flatest+%E6%8A%80%E8%83%BD%E6%8A%BD%E5%8F%96
https://ocg-rule.readthedocs.io/_/api/v3/search/?q=project%3Aocg-rule%2Flatest+%E3%82%AF%E3%82%A4%E3%83%83%E3%82%AF%E3%82%A8%E3%83%95%E3%82%A7%E3%82%AF%E3%83%88
![image](https://github.com/user-attachments/assets/5518202e-9c58-4f82-9204-7c07afc9ad97)
![image](https://github.com/user-attachments/assets/8af832b0-3117-4018-98d6-48f87b78a311)

just default Sphinx's search doesn't work.
I have reviewed the changelog and issues, but still don't know how to fix it.

Or, does the addon search provide a URL somewhere? like this: https://github.com/readthedocs/addons/issues/21#issuecomment-1907870833
Thanks!

**Comment by humitos** [comment]
When performing a search on your project using default Sphinx's search, I see a Javascript error in the console saying that jQuery is not present. The call is done in a `custom.js` file which I guess is something from the project wrote.

Have you updated your Sphinx version recently? Note that newer versions don't install Sphinx by default, so you should install https://pypi.org/project/sphinxcontrib-jquery/ -- could you try installing that extension?

Read the Docs doesn't have control over the default Sphinx's search anymore. We stopped manipulating that code starting on October 7th, 2024. The error you are seeing should be related to Sphinx only.

> And, addon search api can search Chinese or Japanese:

Great! This is what we 100% control 💯 

> does the addon search provide a URL somewhere? like this: [#21 (comment)](https://github.com/readthedocs/addons/issues/21#issuecomment-1907870833)

Nope, we don't provide a link to a direct search using our addons yet as you figured it out 😄

**Comment by lucays** [comment]
> When performing a search on your project using default Sphinx's search, I see a Javascript error in the console saying that jQuery is not present. The call is done in a `custom.js` file which I guess is something from the project wrote.
> 
> Have you updated your Sphinx version recently? Note that newer versions don't install Sphinx by default, so you should install https://pypi.org/project/sphinxcontrib-jquery/ -- could you try installing that extension?
> 
> Read the Docs doesn't have control over the default Sphinx's search anymore. We stopped manipulating that code starting on October 7th, 2024. The error you are seeing should be related to Sphinx only.
> 
> > And, addon search api can search Chinese or Japanese:
> 
> Great! This is what we 100% control 💯
> 
> > does the addon search provide a URL somewhere? like this: [#21 (comment)](https://github.com/readthedocs/addons/issues/21#issuecomment-1907870833)
> 
> Nope, we don't provide a link to a direct search using our addons yet as you figured it out 😄

Thanks, so it's because Sphinx search doesn't support Chinese search itself, and readthedocs search covered this result before.

Now I added html_search_language and html_search_options to conf.py:
https://stackoverflow.com/questions/57221406/why-no-search-result-for-the-cjkchinese-word-in-pythons-documentation-generat
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_search_language
```
html_search_language = "zh"
package_path = [i for i in sys.path if 'site-packages' in i][0]
dict_path = os.path.join(package_path, 'jieba/dict.txt')
print('jieba dict path:', dict_path)
html_search_options = {'dict': dict_path}
```
![image](https://github.com/user-attachments/assets/ceeede79-acb3-4c39-8983-f91f329c42bf)

But it still don't work.

I'll look it up myself again. Anyway, now I know the reason why I can't get result in the search. Thank you!

**Comment by lucays** [comment]
Not quite right... It can actually work now, but it's difficult to use...
search: "技能+抽取"
https://ocg-rule.readthedocs.io/zh-cn/jin-da-yin-shi-yong/search.html?q=%E6%8A%80%E8%83%BD+%E6%8A%BD%E5%8F%96&check_keywords=yes&area=default#
It works.
search: "技能", it also works.

search: "技能抽取", it don't work...
https://ocg-rule.readthedocs.io/zh-cn/jin-da-yin-shi-yong/search.html?q=%E6%8A%80%E8%83%BD%E6%8A%BD%E5%8F%96&check_keywords=yes&area=default#


May I ask how to make the search box of the theme directly use the addon search API?
Now I have to click the flyout to use it...
