### ISSUE TITLE
"This may be an old version of this documentation" warning

### ISSUE THREAD

**Issue by rouault** [readthedocs/addons#402]
Hello,

we use ReadTheDocs infrastructure for https://github.com/OSGeo/PROJ documentation.
Currently we redirect https://proj.org to the latest maintenance branch at https://proj.org/en/9.5/ rather than using the https://proj.org/en/stable tag. We currently get a "This may be an old version of this documentation" warning which is confusing for users, as this is actually the most up to date version of the doc (excepting unreleased "latest" = master). Is there a way to suppress this warning?

**Comment by humitos** [comment]
> Is there a way to suppress this warning?

Yes. You can go to the settings of your project using the new dashboard at https://app.readthedocs.org/. Then going to "Addons -> Notification" and disabling it from there.

**Comment by rouault** [comment]
> Then going to "Addons -> Notification" and disabling it from there.

Ideally I would have liked to be able to tag "9.5" as non-outdated, but "9.4", "9.3" and older as outdated. But disabling all notification is acceptable for now. Thanks for the hint

**Comment by humitos** [comment]
Yeah, I understand. Defining the _outdated_ version is hard to do it in a generic way that works for all the projects. That's why we decided to only work over "stable" and "latest" versions for now. We plan to give users more control on what versions are the outdated one in the future.

**Comment by kbevers** [comment]
> Defining the outdated version is hard to do it in a generic way that works for all the projects.

I think you've done a good job of that by assuming that anything other than `latest` and `stable` is outdated. If the "default version" could be thrown in the mix as a version that's also not outdated we'd be happy. The assumption here of course being that if a project sets a version as the default it's not likely to be outdated.

**Comment by humitos** [comment]
> I think you've done a good job of that by assuming that anything other than latest and stable is outdated. If the "default version" could be thrown in the mix as a version that's also not outdated we'd be happy.

I thought we were doing this already. Maybe there is a bug. I'll check the code to confirm.
