### ISSUE TITLE
Docdiff: showing changes in tables that didn't change

### ISSUE THREAD

**Issue by sciencewhiz** [readthedocs/addons#408]
I noticed that Docdiff shows changes in `.. list-table::` even when no changes were made:

![image](https://github.com/user-attachments/assets/d8d9d681-e167-4005-aa43-3f7e21d9b4d0)

PR Build showing this issue: https://frc-docs--2791.org.readthedocs.build/en/2791/docs/software/telemetry/robot-telemetry-with-annotations.html

**Comment by humitos** [comment]
Thanks for reporting this. We are tracking the same issue in https://github.com/readthedocs/addons/issues/348. Please, subscribe there to get updates.
