### ISSUE TITLE
File tree diff client

### ISSUE THREAD

**Issue by stsewd** [readthedocs/addons#409]
With https://github.com/readthedocs/readthedocs.org/pull/11646/, we are now exposing the file tree diff information to addons, but we still need to have a way to show the results to users.

What I'm thinking here is to have a small list of the changed files (the first 2 or 3 files of each category), and then have a "show all files" button that will open a popup with the list of the files, this list will have some options to filter the results (modified, added, deleted) and a search bar.

We can also expose a button that suggest how to create a redirect for files that were deleted.

**Comment by ericholscher** [comment]
I think to start, even just outputting the data to the console, or as a `<details>` tag in the PR build warning seem like a good initial implantation. Just something where we can start surfacing the data to start playing with in dev.

**Comment by TheTripleV** [comment]
This is nice to have. We currently have a sphinx extension that does this for us with git. https://github.com/wpilibsuite/sphinxext-delta

It injects a new main toctree section that lists all the pages that have changed.

https://frc-docs--2680.org.readthedocs.build/en/2680/index.html

is an example of a PR build with the "pr changed files" toctree added.
We're currently fixing failures in this extension because RTD doesn't inject all the html context anymore.

**Comment by humitos** [comment]
I checked the [API response](https://docs--11716.org.readthedocs.build/_/addons/?client-version=0.19.0&api-version=1&url=https%3A%2F%2Fdocs--11716.org.readthedocs.build%2Fen%2F11716%2Fintro%2Fadd-project.html&project-slug=docs&version-slug=11716) returned at https://docs--11716.org.readthedocs.build/en/11716/

```
        "filetreediff": {
            "diff": {
                "added": [
                    {
                        "file": "guides/management/2fa.html"
                    }
                ],
```

It seems the `file` attribute is not a valid URL, but the path of the file on disk that changed. We will need to resolve all those paths into valid URLs in the backend and expose them to the frontend to generate the links from JavaScript. We can probably add a `url` attribute in the API response as well.
