### ISSUE TITLE
Link previews: sending `url=undefined` sometimes

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#432]
Today I found that if you:

1. go to https://test-builds.readthedocs.io/en/full-feature/shot-scraper.html
2. hover on any of those 3 links
3. you get an error in the console

That's OK because they are external URLs and the backend should block them.

However, when taking a deeper look at the error, it seems the problem is at the JS level because the `url=` attribute sent to the backend API is `undefined` instead the real `href` from the HTML a tag.

The URL hit should be https://test-builds.readthedocs.io/_/api/v3/embed/?url=https://datasette.io/ and the error reported should be `External domain not allowed. domain=datasette.io"`.

@zanderle can you take a look at this? 🙏🏼

**Comment by zanderle** [comment]
It looks like this has already been fixed in https://github.com/readthedocs/addons/pull/433 
https://github.com/readthedocs/addons/blob/d062255265fe526036dee4f8e80fcb227d17aecd/src/linkpreviews.js#L242
