### ISSUE TITLE
Passing `?readthedocs-diff=true` breaks Links Preview

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#460]
Steps to reproduce:
1. Go to https://docs--11751.org.readthedocs.build/en/11751/user-defined-redirects.html?readthedocs-diff=true
2. Hover on "custom domains" under "Root URL redirect at /" section
3. No preview is shown, and no error is reported

If you go to https://docs--11751.org.readthedocs.build/en/11751/user-defined-redirects.html (without `readthedocs-diff`), links preview works properly.

**Comment by agjohnson** [comment]
Noting that passing around the URL param is not necessary either. The diff links could instead:

- Intercept the click event
- Save to local storge or session/etc that doc diff is enabled
- Navigate to original link
- Consume local storage/session/cookie etc

This would avoid passing around the url param. Maybe something to explore here instead.

**Comment by ericholscher** [comment]
This doesn't look like an issue with the GET arg, it's just docdiff in general? I assume because docdiff is replacing page content, it probably unhooks the handlers that are used for link previews or something?

**Comment by humitos** [comment]
> This doesn't look like an issue with the GET arg, it's just docdiff in general? It's replacing the page content, so it's likely the new `a` elements don't have the events on them.

Good point. However, the `a` node seems to be the one we modified already since it has the class `link-preview` on it and it shows the dot underlined

![Screenshot_2024-12-04_14-09-59](https://github.com/user-attachments/assets/7bb5a21e-5bb7-4de3-92f2-fd4678a4dd27)

The problem seems to be the JavaScript event being deleted somehow.

**Comment by humitos** [comment]
Probably, a first step here would be to _disable links preview_ when the docdiff is enabled? At least, that will remove the confusion of having these elements with dot underline where I'm expecting to trigger links preview.

**Comment by humitos** [comment]
> Looking at MDN, it seems we need a live nodelist, instead of a static one: [developer.mozilla.org/en-US/docs/Web/API/NodeList#live_vs._static_nodelists](https://developer.mozilla.org/en-US/docs/Web/API/NodeList#live_vs._static_nodelists)

I'm not sure to follow how this would help us here 🤔

**Comment by humitos** [comment]
> If we want them to continue working, we probably need some way to retrigger the link selector logic after doing the replacement of the page content.

I suppose we will want DocDiff to trigger `READTHEDOCS_DOCUMENT_BODY_CHANGED` or similar, so other addons can subscribe to it and update themselves. In the case of links preview, re-run the [`setupTooltip`](https://github.com/readthedocs/addons/blob/6fe4e16c073513c43f5bca9980445364d97ee114/src/linkpreviews.js#L24) function.

This will be similar to what we are implementing for SPA in https://github.com/readthedocs/addons/issues/157. I think these issues are related, so we may want to wait for that other issue to set the pattern here and we can use it here.

**Comment by humitos** [comment]
> This would avoid passing around the url param. Maybe something to explore here instead.

I found another issue when passing the URL param: #461. I opened https://github.com/readthedocs/addons/pull/462 to fix it for now and to start thinking about the idea anything external that enables/disables an add should be done via an event, so all the other addons that needs to update an internal state can do it.

**Comment by ericholscher** [comment]
Is this already fixed in https://github.com/readthedocs/addons/pull/441/ ?
