### ISSUE TITLE
Correct import for ethical-ad-client

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/addons#6]
This is also an issue with the ea-client, just noting here to find a solution.

The fix for the import statement is that the ea-client package.json is wrong.
The `main` configuration option points to a file that doesn't exist.

`main: "dist/ethicalads.js"` at the ethical-ad-client package configuration solves the import problems here,
and `import "ethical-ad-client"` worked with this change.

**Comment by humitos** [comment]
This is related to #5 and I think we need to do some work there first.
