### ISSUE TITLE
Ads: migrate AdBlocker nag logic from old .js file

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#68]
There are some logic to put a message in the console (nag) when the person is using an adblocker or similar.

**Comment by davidfischer** [comment]
I don't really know how effective this logic is, but it is reasonably easy to add since the existing `doc-embed.js` does it. With that said, if it didn't make it into the new addons, that would probably be OK.

**Comment by ericholscher** [comment]
I think it's probably safe to just not do this.
