### ISSUE TITLE
Remove old assets inclusion/generation at build process

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#72]
We are generating some `.js` files and we are including some other static files. Mainly in MkDocs.

We should remove them from the build process once we are using the new addons approach. See the code to remove at https://github.com/readthedocs/readthedocs.org/blob/6f394fd89a34e636de30fc23268bb51b7c85028b/readthedocs/doc_builder/backends/mkdocs.py#L170-L180

Note there are a bunch of tests and other related things we can remove as well.

Issues:

* Closes https://github.com/readthedocs/readthedocs.org/issues/10803
* Closes https://github.com/readthedocs/meta/issues/85
* Related https://github.com/mkdocs/mkdocs/discussions/3413

**Comment by humitos** [comment]
Take a look at this comment in https://github.com/readthedocs/meta/issues/85#issuecomment-1616690964

**Comment by ericholscher** [comment]
> We are generating some `.js` files and we are including some other static files. Mainly in MkDocs.
> 
> We should remove them from the build process once we are using the new addons approach. See the code to remove at https://github.com/readthedocs/readthedocs.org/blob/6f394fd89a34e636de30fc23268bb51b7c85028b/readthedocs/doc_builder/backends/mkdocs.py#L170-L180
> 
> Note there are a bunch of tests and other related things we can remove as well.

This is also being included in Sphinx via our extension:

https://github.com/readthedocs/readthedocs-sphinx-ext/blob/7c60d1646c12ac0b83d61abfbdd5bcd77d324124/readthedocs_ext/_templates/readthedocs-insert.html.tmpl#L21-L33

**Comment by pawamoy** [comment]
Coming from https://github.com/readthedocs/readthedocs.org/issues/7844.

I opened https://github.com/mkdocs/mkdocs/discussions/3413 to start a discussion about https://github.com/readthedocs/readthedocs.org/issues/10803. Do I understand correctly that the addons approach will remove the need to safely load and re-dump MkDocs config file to inject your own configuration? Meaning that any custom tag MkDocs might implement in the future would be immediately supported by ReadTheDocs?

**Comment by stsewd** [comment]
@pawamoy yeah, overriding the mkdocs config isn't required with this approach.

**Comment by humitos** [comment]
I took a look at the [`conf.py.tmpl`](https://github.com/readthedocs/readthedocs.org/blob/83805a643d56764f893ff65f764bf993c74fb582/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl) that we append on Sphinx projects and I was thinking on a way to detect _what projects are using what variables from the context_. Is there any way we can achieve this?

**Comment by ericholscher** [comment]
I think we can probably wrap the function in some hacky way so that it logs a message or something? It would definitely be a hack or a monky patch though 🙈

**Comment by humitos** [comment]
I tested this locally and it fails when pickling the Sphinx environment at https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/__init__.py#L330

I think there is some modifications to the code we can make to make this object picklable. I tried to disable pickling the environment on Sphinx but I didn't find a configuration for that.

**Comment by ericholscher** [comment]
This is what I was imagining when I said a hack or monkey patch :) It's a reasonable way to get that data. 💯

**Comment by humitos** [comment]
Interesting, I've tried the `__getstate__` and `__setstate__` already, but I wasn't aware of that `__reduce__`. I can try that as well and see what happens.

**Comment by humitos** [comment]
I tried that and I wasn't able to make it work. There is something else happening here withe Sphinx environment that contains this object. I can pickle _ReadTheDocsSphinxContext_ without problems by calling `pickle.dump(...)`, as Sphinx calls, and it works. However, when it's called from Sphinx itself it doesn't work 🤷🏼

**Comment by humitos** [comment]
I'm pretty close, but it seems because of this line: https://github.com/sphinx-doc/sphinx/blob/fa290049515c38e68edda7e8c17be69b8793bb84/sphinx/builders/html/__init__.py#L561

a new object is created and we lost control of it. I tried to override the `__or__` in our object, but since it's a the right of the operation our method is not called, but the other object instead (a real `dict`).

I still think this approach _could_ work, but it definitely needs more testing.

**Comment by humitos** [comment]
This is the code I've been playing with:

```python
class ReadTheDocsSphinxContext(dict):

    # obj[key]
    def __getitem__(self, name):
    # def __class_getitem__(cls, key):
        READTHEDOCS_INJECTED_KEYS = [
            'html_theme',
            'current_version',
            'version_slug',
            'MEDIA_URL',
            'STATIC_URL',
            'PRODUCTION_DOMAIN',
            'proxied_static_path',
            'versions',
            'downloads',
            'subprojects',
            'slug',
            'name',
            'rtd_language',
            'programming_language',
            'canonical_url',
            'analytics_code',
            'single_version',
            'conf_py_path',
            'api_host',
            'github_user',
            'proxied_api_host',
            'github_repo',
            'github_version',
            'display_github',
            'bitbucket_user',
            'bitbucket_repo',
            'bitbucket_version',
            'display_bitbucket',
            'gitlab_user',
            'gitlab_repo',
            'gitlab_version',
            'display_gitlab',
            'READTHEDOCS',
            'using_theme',
            'new_theme',
            'source_suffix',
            'ad_free',
            'docsearch_disabled',
            'user_analytics_code',
            'global_analytics_code',
            'commit',
        ]

        if name in READTHEDOCS_INJECTED_KEYS:
            print(f"INFO: Read the Docs value from injected context called. {name=}")

            breakpoint()
        return super().__getitem__(name)

    # obj.key
    def __getattribute__(self, name):
        READTHEDOCS_INJECTED_KEYS = [
            'html_theme',
            'current_version',
            'version_slug',
            'MEDIA_URL',
            'STATIC_URL',
            'PRODUCTION_DOMAIN',
            'proxied_static_path',
            'versions',
            'downloads',
            'subprojects',
            'slug',
            'name',
            'rtd_language',
            'programming_language',
            'canonical_url',
            'analytics_code',
            'single_version',
            'conf_py_path',
            'api_host',
            'github_user',
            'proxied_api_host',
            'github_repo',
            'github_version',
            'display_github',
            'bitbucket_user',
            'bitbucket_repo',
            'bitbucket_version',
            'display_bitbucket',
            'gitlab_user',
            'gitlab_repo',
            'gitlab_version',
            'display_gitlab',
            'READTHEDOCS',
            'using_theme',
            'new_theme',
            'source_suffix',
            'ad_free',
            'docsearch_disabled',
            'user_analytics_code',
            'global_analytics_code',
            'commit',
        ]

        if name in READTHEDOCS_INJECTED_KEYS:
            print(f"INFO: Read the Docs value from injected context called. {name=}")
            breakpoint()

        return super().__getattribute__(name)

    def __or__(self, other):
        print("__or__ called")
        breakpoint()

        result = super().__or__(other)
        return ReadTheDocsSphinxContext(result)


html_context = ReadTheDocsSphinxContext({"slug": "project-slug", "commit": "a1b2c3"})

templates_path = [
    "templates",
]

# Remove the following warning
#
# WARNING: The config value `html_context' has type `ReadTheDocsSphinxContext', defaults to `dict'.
#


# def env_updated(app, env):
def html_page_context(app, pagename, templatename, context, doctree):
    app.builder.globalcontext = ReadTheDocsSphinxContext(app.builder.globalcontext)
    breakpoint()


def readthedocs_context(app, config):
    config._raw_config["__builtins__"]["ReadTheDocsSphinxContext"] = ReadTheDocsSphinxContext


def setup(app):
    app.connect("config-inited", readthedocs_context)
    app.connect("html-page-context", html_page_context)
    # app.connect("env-updated", env_updated)
```

**Comment by humitos** [comment]
> If we aren't planning to remove these config items, I'm not 100% sure we need to know which are being used.

Not sure what you mean exactly with this. My goal here to remove the injection of the `conf.py.tmpl` completely eventually and have parity between `build.jobs` and `build.commands`: Read the Docs does not inject _anything_ behind the scenes with this magic approach.

Instead, all the _important/useful_ variables are passed via environment variables (as we are doing with `READTHEDOCS_` ones) to all the commands executed.

The work I was describing with this approach was to know who was using these variables to:

* be able to only send an email to those users
* know what are those _important/useful_ variables we should convert into environment variables

**Comment by ericholscher** [comment]
Gotcha -- if the goal is to know who to email, I think we can just email _all active Sphinx/Mkdocs projects_. It's a big enough change it's likely worth letting people know about, likely at the same time as Addons.

In terms of "which data is important", that is harder to get without this approach.

**Comment by humitos** [comment]
OK, let's say this approach is complex to implement and fragile to make it work in all versions, discard it for a moment and talk about a different one: "don't add any magic to our build process and evaluate these variables one by one, checking if they are used in code we control (`readthedocs.org`, `readthedocs-sphinx-ext` and `sphinx_rtd_theme`):

| Variable | Used | Where |
| -------- | ---- | ----- |
| html_theme | ✅ | [data.js.tmpl](https://github.com/readthedocs/readthedocs.org/blob/5cc6cf40663b36c5325aa52e4bf825951894be3f/readthedocs/doc_builder/templates/doc_builder/data.js.tmpl#L10): won't be used since we are removing that file anyways. [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L82-L93): inject CSS based on theme |
| current_version | ✅ |  [data.js.tmpl](https://github.com/readthedocs/readthedocs.org/blob/5cc6cf40663b36c5325aa52e4bf825951894be3f/readthedocs/doc_builder/templates/doc_builder/data.js.tmpl#L7): add it to `READTHEDOCS_DATA`. [versions.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/versions.html#L6): render the flyout statically at build time. [layout.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/layout.html#L120-L134): used under undocumented variable `theme_display_version`. [external_version_warning.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/external_version_warning.py#L40): replaced by addons |
| version_slug | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L148): dump it into js file |
| MEDIA_URL | ❌  |  |
| STATIC_URL | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L80): generate CSS URL |
| PRODUCTION_DOMAIN | ✅ | [versions.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/versions.html#L24-L30): generate links on the flyout |
| proxied_static_path | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L80): generate proxied URLs. [readthedocs-doc-embed.js](https://github.com/readthedocs/readthedocs.org/blob/5cc6cf40663b36c5325aa52e4bf825951894be3f/readthedocs/core/static-src/core/js/readthedocs-doc-embed.js#L26): automatically inject jQuery. [rtd-data.js](https://github.com/readthedocs/readthedocs.org/blob/5cc6cf40663b36c5325aa52e4bf825951894be3f/readthedocs/core/static-src/core/js/doc-embed/rtd-data.js#L61): modifies `READTHEDOCS_DATA` js object |
| versions | ✅ | [versions.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/versions.html#L12-L14): generate flyout statically |
| downloads | ✅ | [versions.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/versions.html#L17-L20): generate flyout statically |
| subprojects | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L161): dump into js object |
| slug | ✅ | [versions.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/versions.html#L24-L30): generate flyout statically |
| name | ❌ |  |
| rtd_language | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L149): dump into js object |
| programming_language | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L150): dump into js object |
| canonical_url | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L151): dump into js object |
| analytics_code | ❌ |  |
| single_version | ❌ |  |
| conf_py_path | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L154): dump into js object. [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| api_host | ❌ |  |
| github_user | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| proxied_api_host | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L168-L169): dump into js object. |
| github_repo | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| github_version | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| display_github | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| bitbucket_user | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| bitbucket_repo | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| bitbucket_version | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| display_bitbucket | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| gitlab_user | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| gitlab_repo | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| gitlab_version | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| display_gitlab | ✅ | [breadcrumbs.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/breadcrumbs.html#L39-L53): generate "Edit on.." links |
| READTHEDOCS | ✅ | Everywhere 😄 |
| using_theme | ❌ |  |
| new_theme | ❌ |  |
| source_suffix | ✅ |  |
| ad_free | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L158): dump into js object. |
| docsearch_disabled |  ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L163): dump into js object. |
| user_analytics_code |  ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L160): dump into js object.   |
| global_analytics_code | ✅ | [readthedocs.py](https://github.com/rtfd/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L159): dump into js object.   |
| commit | ✅ | [footer.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/sphinx_rtd_theme/footer.html#L36): display the commit at bottom |

**Comment by humitos** [comment]
I can get some information from the previous table:

* Lot of these context variables won't be needed when migrating to addons
* All the ones that are dumped into the js file aren't required when migrating to addons
* A few of them are using directly by our theme
* We can start by removing the ones that we know _we_ are not using and see what happens
* I'd propose to _immediately pass the useful ones as environment variables_ and _adapt our theme_ to start using them:
  * `READTHEDOCS`
  * `READTHEDOCS_GIT_COMMIT_HASH`

### Proposed Sphinx migration plan

1. Remove the ones we already know we are not using
2. Update our theme to use environment variables instead of context variables (`READTHEDOCS` and `READTHEDOCS_GIT_COMMIT_HASH`)
3. Implement new addons on our theme (https://github.com/readthedocs/sphinx_rtd_theme/pull/1526)
4. Release a new version of our theme
5. Figure it out how to generate "Edit on..." links in a clean way (I doubt there is one without too much magic, see https://github.com/readthedocs/readthedocs.org/blob/5cc6cf40663b36c5325aa52e4bf825951894be3f/readthedocs/proxito/views/hosting.py#L377-L392). As a example, [`furo` uses our own magic](https://github.com/pradyunsg/furo/blob/main/src/furo/theme/furo/components/edit-this-page.html#L23) if the variables are available --removing these variables won't break docs at least 👍🏼 [^1]
6. Write a blog post explaining this deprecation to communicate this to our users
7. Enable addons by default on new projects together with this behavior (don't install `readthedocs-sphinx-ext` and don't append `conf.py.tmpl` to them)

At this point, all new projects will be using the latest version of our theme that implements the flyout using addons and we won't be adding any magic behind the scenes (not installing `readthedocs-sphinx-ext` and not appending `conf.py.tmpl`)


### Proposed MkDocs migration plan

1. Write a blog post communicating this new behavior
2. Enable addons by default on new MkDocs projects and stop calling [`append_conf`](https://github.com/readthedocs/readthedocs.org/blob/5cc6cf40663b36c5325aa52e4bf825951894be3f/readthedocs/doc_builder/backends/mkdocs.py#L133-L276) to modify their `mkdocs.yml`


At this point, we won't be manipulating `mkdocs.yml` (which will immediately solve https://github.com/readthedocs/readthedocs.org/issues/8529 as well) and building on Read the Docs will be exactly the same as building locally.


[^1]: I may be 👍🏼 on dropping this feature if we don't find a clean/generic way of supporting this, since I don't know how useful it is anyways.

**Comment by ericholscher** [comment]
We are already setting the `READTHEDOCS` & `READTHEDOCS_GIT_COMMIT_HASH ` env var along with some others: https://docs.readthedocs.io/en/stable/reference/environment-variables.html

**Comment by ericholscher** [comment]
Seems like a good test case for doing the Sphinx migration later 👍

**Comment by humitos** [comment]
The `BaseMkDocs.append_conf` method checks for `Feature.MKDOCS_THEME_RTD` and inject our own theme if it's not explicitly defined in the project. We [tried to removed this feature flag in the past](https://github.com/readthedocs/readthedocs.org/pull/4556) but we found there were some projects still depending on us setting the `readthedocs` theme --so we added those projects to the new feature flag to keep this behavior, but removed this magic from the builder for all new projects.

We added a log line in https://github.com/readthedocs/readthedocs.org/blob/217c5bc65fe551b264dc11608f263b68e2f652af/readthedocs/doc_builder/backends/mkdocs.py#L52-L66 to know what are those projects.

I used this log line to check New Relic at https://onenr.io/0BQroa8ZnwZ and we only have **only 2 projects using this feature flag** that belong to the same organization. So, this change will be a pretty low impact change and easy to fix by the customer. They just need to define `theme.name: readthedocs` in their `mkdocs.yml` file: https://www.mkdocs.org/user-guide/configuration/#theme

**Comment by humitos** [comment]
Small updates here:

* The MkDocs plan was already executed, https://github.com/readthedocs/readthedocs.org/pull/11206 is merged and we are defaulting to addons for MkDocs projects
* I opened a discussing on Furo's Sphinx theme explaining that we plan to remove the `conf.py` manipulation at https://github.com/pradyunsg/furo/discussions/785 to coordinate the work with them

**Comment by humitos** [comment]
> I tried to override the `__or__` in our object, but since it's a the right of the operation our method is not called, but the other object instead (a real `dict`).

I think we need to use [`__ior__`](https://docs.python.org/3/reference/datamodel.html#object.__ior__) here since the left operand will return `NotImplemented` and call _ours_ after that. 🚧  I want to give this another try and double check if it works.

**Comment by humitos** [comment]
My plan here is to recover the work done in https://github.com/readthedocs/addons/issues/72#issuecomment-1919452042 and create a small `sphinx/builders/html/__init__.py.patch` to apply it on projects building with Sphinx and be able to log what are the projects using these variables. I will create a feature flag for this so we can disable it in an easy way if we detect it breaks for some reason.

I knot this is a little hacky, but it's better to be able to get this data and contact users than just remove everything without contacting anybody and breaking people's documentation without advice.

With that data, we will be ready to move forward with the plan.

**Comment by humitos** [comment]
I jumped into this again and I found it's pretty hard to make our original idea to work. Summarizing, we won't be able to inject or mock Sphinx code to know _who_ is using our injected context. Why? Because, Sphinx and Jinja2 perform _a lot of operations_ on the context and many of them are casting the object to a regular `dict`.

Some code I found useful while doing the research:
* https://github.com/sphinx-doc/sphinx/blob/f85f50e52614c627adbcf43629ca028829454081/sphinx/builders/html/__init__.py#L1120
* https://github.com/pallets/jinja/blob/9c6c3198996014756c111ac4d2e80b0423b3b95a/src/jinja2/environment.py#L1289
* https://github.com/pallets/jinja/blob/9c6c3198996014756c111ac4d2e80b0423b3b95a/src/jinja2/runtime.py#L93
* https://github.com/pallets/jinja/blob/9c6c3198996014756c111ac4d2e80b0423b3b95a/src/jinja2/runtime.py#L145

This is the patch I was testing: https://gist.github.com/humitos/fc79732425c2d8d7d026d8fab3e52919

----

So, that said, I think we should just follow our deprecation path here: contact users (_all of them?_ 🤷🏼 , blog post, brown dates, etc). Thoughts?

**Comment by ericholscher** [comment]
Seems like we have work to do to move forward here, since we're still depending on these variables in a bunch of places? (https://github.com/readthedocs/addons/issues/72#issuecomment-1926580069) 

I'm not 100% clear on what we're deprecating here, so we should probably make that explicit if possible.

**Comment by humitos** [comment]
We are deprecating  the manipulation of the Sphinx's `conf.py` file and installation of `readthedocs-sphinx-ext`. That means:

- No Sphinx context injection (all the variables from the comment you linked won't be available on Sphinx). 
  - Nothing should hard break, but there will be small features that won't be available anymore (e.g. "Edit on GitHub" links on breadcrums or "Revision a1b2c3" at the footer)
  - The footer will be generated by addons now, so we don't need variables for that (e.g. `PRODUCTION_DOMAIN`)
  - Many of variables are used to inject `READTHEDOCS_DATA` object in the HTML, but that's not needed anymore with addons
- No pull request / version warning added by our extension
- No `.fjson` files will be generated by our extension

I think the deprecation path here consists in:
1. Release the version of our theme that uses addons to generate the flyout
2. Define a future date with enough time to people to migrate and us to perform the changes and do some testing
3. Write the blog post and send emails to all active Sphinx projects announcing this deprecation

Note that we won't have a 1:1 feature parity with this migration and I don't pretend that since it will be definitely impossible. We are deprecating old features we won't maintain anymore. Users will still be able to implement some of them by themselves by adding extra configurations to their `conf.py` if they want to keep these.

**Comment by humitos** [comment]
Another idea here is to disable `conf.py` manipulation and the installation of `readthedocs-sphinx-ext` if addons is enabled. Plus, enabling addons for all new projects by default. This could help us knowing if these users are using the injected context as well while moving one step forward.

**Comment by humitos** [comment]
During our last 1on1 we talked about developing a Sphinx extension that tries to replicate the behavior we are deprecating. This would allow users/authors/theme developers that _really want the context manipulation done by Read the Docs_ to keep compatibility while they migrate to the new behavior.

I created [sphinx-build-compatibility](https://github.com/readthedocs/sphinx-build-compatibility/) to keep this compatibility for now with those projects that want to opt-in.

The **new plan** after our 1on1:
1. Merge https://github.com/readthedocs/readthedocs.org/pull/11441 
2. Add a new `test-builds-sphinx-context` project with `DISABLE_SPHINX_MANIPULATION=True` and check the [sphinx context](https://test-builds.readthedocs.io/en/latest/sphinx-context.html) page in that project [^1]
3. Write a blog post communicating the new behavior
4. If we don't find anything breaking, enable `DISABLE_SPHINX_MANIPULATION` to all **new** projects
5. Tell users _wanting the old behavior_ to install `sphinx-build-compatibility` on support requests
6. Enable `DISABLE_SPHINX_MANIPULATION` to **all** projects
7. Remove `DISABLE_SPHINX_MANIPULATION` feature flag when we are happy with it
8. At this point **all our users will be using Read the Docs Addons**

I think this gives us pretty clear steps on how to move forward with this deprecation and tackle the issues we may find as we go. Note that I'm saying to do one step at a time and wait some weeks before performing the next one. @ericholscher thoughts?

[^1]: my test using the development environment worked successfully 🎉

**Comment by ericholscher** [comment]
@humitos That's awesome you figured out a good way to get this working. Looking at the code, the current integration path for the full historical data is pretty complex, but I imagine most users will only want a subset, so hopefully we can simplify the integration pattern for folks in the future who just want "A list of current versions and translations", which is likely just pulling that from the env. 

This makes me a lot more confident in pushing forward with deprecation in a faster timeline :100:

**Comment by humitos** [comment]
Great! I'd appreciate if you review that PR so we can move forward with the first 3 steps for now to perform our tests. Those steps dont' affect users.

----

> the current integration path for the full historical data is pretty complex

I've done it this way only to keep backward compatibility; but we won't maintain this extension too longer since it's a deprecated behavior we want to get rid of completely. That's the idea.

> folks in the future who just want "A list of current versions and translations", which is likely just pulling that from the env.

Ideally, they should use the APIv3 for this (https://docs.readthedocs.io/en/stable/api/v3.html#versions-listing) with an API Token [^1]. I'd prefer to not inject all this data by default because those are expensive queries for our database depending on the size of the project and 99% of users don't use/need it.


[^1]: in the future, we should support per-project API tokens to avoid using per-user tokens for this cases (see https://github.com/readthedocs/readthedocs.org/issues/7928 and https://github.com/readthedocs/readthedocs.org/issues/10405).

**Comment by humitos** [comment]
All the projects have been migrated to the new addons and the Sphinx context is not injected anymore 🎉 . This is a great and big step. Now, be prepared to attend users and customers support requests during the following days/weeks 😄
