### ISSUE TITLE
Search: when hitting `/` it shows the modal but it does not focus it

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#78]
The focus goes to the default search input from Sphinx. I'm testing this locally in http://test-builds.devthedocs.org/en/manual-integrations/

I think it's because our theme is catching this event as well.

**Comment by agjohnson** [comment]
More of a general note, but we should be careful with what hotkeys are are overriding. It's possible to interfere with both browser native hotkeys, OS native hotkeys, and hotkeys used by accessibility tooling and screen readers.

Here is the [WebAIM guidance on keyboard accessibility and accesskeys](https://webaim.org/techniques/keyboard/accesskey), which notes to be careful with single key hotkeys. Screen readers can also use the full keyboard for providing navigation.

I don't know that `/` specifically would be an issue though, maybe there is a resource that lists safe key combinations.

**Comment by humitos** [comment]
Yes. This is something I'd like to discuss more and use a standard pattern or something well supported by browsers if possible. I had the same concern when working on the docdiff hotkey: https://github.com/readthedocs/addons/pull/63#issuecomment-1634289746

I think it's worth to do some research and understand what's the right way to do this and stick with that pattern 👍🏼

**Comment by humitos** [comment]
With #108 happens the same. Example:

![Peek 2023-09-06 12-08](https://github.com/readthedocs/addons/assets/244656/9fa98258-77b6-463d-bda3-5df761fa6038)
