### ISSUE TITLE
Notification: make notifications permanently dismissable

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/addons#87]
When viewing a pull request build, if I dismiss the pull request warning notification then navigate around back to the top level page, I get the notification again. This could be a little annoying to dismiss repeatedly.

Instead, we should probably track this with a cookie and only show the notification if it hasn't been dismissed by the user.

**Comment by humitos** [comment]
We are tracking this at https://github.com/readthedocs/addons/issues/46
