### ISSUE TITLE
Enabling search breaks flyout

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#91]
It seems there is a race-condition or similar between the addons. Uncommenting search, makes flyout to not be shown. However, putting the flyout initialization _after_ the search one, makes the flyout to be shown but the search doesn't work.

Even, uncommenting the search addon, makes the EthicalAd one to not be displayed.

I'm pretty confused here 🤷🏼

**Comment by zanderle** [comment]
@humitos does this happen locally for you? Are you seeing any errors in the console?

**Comment by humitos** [comment]
This happen to me locally when loading a documentation site using Read the Docs development instance

To reproduce it, I do:

1. From `readthedocs.org` repository, I run `inv docker.up --no-search`
2. On `addons` repository, I run `npm run dev`
3. I uncomment line https://github.com/readthedocs/readthedocs-client/blob/d51a83c82bf0d28b2bc2e89ef27fe4cb09ea78da/src/index.js#L32 to enable search
4. I open http://test-builds.devthedocs.org/en/manual-integrations/

The error I see in the console is `TypeError: can't convert undefined to object`. Clicking on the error I see this

![Screenshot_2023-08-30_15-30-25](https://github.com/readthedocs/addons/assets/244656/69ea8d12-ccac-49dc-ab72-45630090e56e)


That said, I cannot reproduce this error when using http://localhost:8000/ 🤷🏼 .

Is there anything else I can provide here to help you to debug?

**Comment by humitos** [comment]
Hrm... Thinking a little more on this. It's probably an issue with the API response 🤔

**Comment by humitos** [comment]
I double-checked the API responses on both and I didn't find anything different 🤷🏼

**Comment by humitos** [comment]
I put a break there. In the second iteration `aucmds` is `undefined`. That's why it fails. I don't know why it's `undefined` or what that object is, even, but this is something at least 😄 

![Screenshot_2023-08-30_15-47-39](https://github.com/readthedocs/addons/assets/244656/e0a18c35-6312-489f-946e-8bd8eff09815)

**Comment by humitos** [comment]
It seems that file comes from https://github.com/tridactyl/tridactyl/blob/master/src/excmds.ts 😞

**Comment by humitos** [comment]
However, it doesn't seem to be the issue, even if it shows an error in the console.

In fact, if I disable `FlyoutAddon`, the `NotificationAddon` is shown. So, there is a race condition when initializing the addons.

**Comment by humitos** [comment]
On Chrome I see no errors at all, but the Flyout is not shown when enabling Search.

**Comment by humitos** [comment]
I found and solve this issue at https://github.com/readthedocs/addons/pull/99
