### ISSUE TITLE
Docdiff: Work with CORS, authentication, etc

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/addons#93]
This might be less an issue of this library and more of a change destined for the application. It's going to be rather easy to run into CORS issues here (surprise!), and on the commercial side, authentication. Custom domains, authentication, and some non-standard set ups will not be supported well currently.

We could consider if this warrants an API, or something similar, to fetch the page from storage. This seems like it would need a token of sorts to be safe. This would give the library the ability to request the page for DOM comparison without being concerned about all of the pieces in the middle.

**Comment by agjohnson** [comment]
@humitos I saw you merged some docdiff changes, but we probably should resolve this before we point users and customers to this feature. At very least this should be a different domain

**Comment by agjohnson** [comment]
The domain here does not look to be in use anymore, but there is an issue on commercial with the request. Need to talk more here, but could start testing with community and public versions.

**Comment by humitos** [comment]
I enabled the feature flag in production to test this out and it's blocked by CORS. Example: https://test-builds--2110.org.readthedocs.build/en/2110/

![Screenshot_2023-09-14_13-03-21](https://github.com/readthedocs/addons/assets/244656/f6b21a9e-588f-4889-ad17-1f40110a43fd)


We talked about enabling CORS on public versions only for now, so I will give that a try.

**Comment by stsewd** [comment]
Allowing authed cross site requests implies a security risk, so this issue isn't totally solved with the CORS change.

**Comment by humitos** [comment]
We deployed the CORS changes and it's working fine. The work related with addons + CORS is already solved.

If there are more work related to CORS, cleanup or more strict configuration, I'd suggest to open an issue in -ops or .org repositories.
